apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      automountServiceAccountToken: false  # Disable service account token mounting
      volumes:
        - name: orders-storage
          persistentVolumeClaim:
            claimName: orders-pvc
      containers:
      - name: orders
        image: orders-service:v1.0.0
        resources:
          requests:
            cpu: "200m"    # 0.2 CPU core
            memory: "256Mi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "400m"    # 0.4 CPU core
            memory: "512Mi"
            ephemeral-storage: "2Gi"
        ports:
        - containerPort: 50052
        volumeMounts:
          - name: orders-storage
            mountPath: /app/data
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders-service
  ports:
  - port: 50052
    targetPort: 50052
  type: ClusterIP
